# Select image from https://hub.docker.com/_/php/
image: php:7.4

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
cache:
  paths:
    - vendor/

before_script:
  # Install dependencies
  - bash ci/docker_install.sh > /dev/null

# We test PHP 7.1
test:7.1:
  image: php:7.1
  script:
    - composer run test-post-type

# We test PHP 7.2
test:7.2:
  image: php:7.2
  script:
    - composer run test-post-type

# We test PHP 7.3
test:7.3:
  image: php:7.3
  script:
    - composer run test-post-type
