<?php

declare(strict_types=1);

namespace BackTo\Framework\Bundle\Security\Network;

use BackTo\Framework\Bundle\Security\Contracts\FileWriterInterface;
use BackTo\Framework\Bundle\Security\Infrastructure\NativeFileWriter;

/**
 * Generates Nginx and Apache configuration snippets for bot protection.
 *
 * All settings are injected via setters from the DI container
 * (see ConfigureServerConfigGeneratorPass). Defaults match those
 * defined in SecurityConfiguration::getDefaults().
 */
final class ServerConfigGenerator
{
    /** @var string[] User-Agent patterns to block */
    private array $blockedUserAgents = [];

    /** @var string[] URI patterns considered sensitive */
    private array $sensitiveEndpoints = [];

    private int $globalRateLimit = 10;
    private int $globalBurst = 20;
    private int $sensitiveRateLimit = 2;
    private int $sensitiveBurst = 3;
    private int $maxConnPerIp = 20;
    private bool $blockEmptyUserAgent = true;

    /** @var string[] IP addresses or CIDR ranges to block */
    private array $blockedIps = [];

    private readonly FileWriterInterface $fileWriter;

    public function __construct(?FileWriterInterface $fileWriter = null)
    {
        $this->fileWriter = $fileWriter ?? new NativeFileWriter();
    }

    /**
     * @param string[] $userAgents
     */
    public function setBlockedUserAgents(array $userAgents): self
    {
        $this->blockedUserAgents = $userAgents;

        return $this;
    }

    /**
     * @param string[] $userAgents
     */
    public function addBlockedUserAgents(array $userAgents): self
    {
        $this->blockedUserAgents = array_unique(
            array_merge($this->blockedUserAgents, $userAgents),
        );

        return $this;
    }

    /**
     * @param string[] $endpoints
     */
    public function setSensitiveEndpoints(array $endpoints): self
    {
        $this->sensitiveEndpoints = $endpoints;

        return $this;
    }

    public function setGlobalRateLimit(int $requestsPerSecond, int $burst): self
    {
        $this->globalRateLimit = $requestsPerSecond;
        $this->globalBurst = $burst;

        return $this;
    }

    public function setSensitiveRateLimit(int $requestsPerSecond, int $burst): self
    {
        $this->sensitiveRateLimit = $requestsPerSecond;
        $this->sensitiveBurst = $burst;

        return $this;
    }

    public function setMaxConnectionsPerIp(int $max): self
    {
        $this->maxConnPerIp = $max;

        return $this;
    }

    public function setBlockEmptyUserAgent(bool $block): self
    {
        $this->blockEmptyUserAgent = $block;

        return $this;
    }

    /**
     * @param string[] $ips IP addresses or CIDR ranges
     */
    public function setBlockedIps(array $ips): self
    {
        $this->blockedIps = $ips;

        return $this;
    }

    /**
     * @return array{blocked_user_agents: string[], blocked_ips: string[], sensitive_endpoints: string[], global_rate_limit: int, global_burst: int, sensitive_rate_limit: int, sensitive_burst: int, max_connections_per_ip: int, block_empty_user_agent: bool}
     */
    public function getConfiguration(): array
    {
        return [
            'blocked_user_agents' => $this->blockedUserAgents,
            'blocked_ips' => $this->blockedIps,
            'sensitive_endpoints' => $this->sensitiveEndpoints,
            'global_rate_limit' => $this->globalRateLimit,
            'global_burst' => $this->globalBurst,
            'sensitive_rate_limit' => $this->sensitiveRateLimit,
            'sensitive_burst' => $this->sensitiveBurst,
            'max_connections_per_ip' => $this->maxConnPerIp,
            'block_empty_user_agent' => $this->blockEmptyUserAgent,
        ];
    }

    public function generateNginx(): string
    {
        $lines = [];
        $lines[] = '# ============================================================';
        $lines[] = '# Bot protection — generated by BackTo Framework Security Bundle';
        $lines[] = '# Include this file in your http {} or server {} block.';
        $lines[] = '# ============================================================';
        $lines[] = '';

        $lines[] = '# --- Rate limiting zones (place in http {} block) ---';
        $lines[] = sprintf(
            'limit_req_zone $binary_remote_addr zone=backto_global:%s rate=%dr/s;',
            '10m',
            $this->globalRateLimit,
        );
        $lines[] = sprintf(
            'limit_req_zone $binary_remote_addr zone=backto_sensitive:%s rate=%dr/s;',
            '10m',
            $this->sensitiveRateLimit,
        );
        $lines[] = sprintf(
            'limit_conn_zone $binary_remote_addr zone=backto_conn:%s;',
            '10m',
        );
        $lines[] = '';

        $lines[] = '# --- Place the following inside your server {} block ---';
        $lines[] = '';

        // User-Agent blocking
        if ($this->blockedUserAgents !== []) {
            $pattern = implode('|', array_map(
                fn (string $ua): string => preg_quote($ua, '/'),
                $this->blockedUserAgents,
            ));
            $lines[] = '# Block known bot User-Agents';
            $lines[] = sprintf('if ($http_user_agent ~* (%s)) {', $pattern);
            $lines[] = '    return 403;';
            $lines[] = '}';
            $lines[] = '';
        }

        // Empty User-Agent blocking
        if ($this->blockEmptyUserAgent) {
            $lines[] = '# Block requests with empty User-Agent';
            $lines[] = 'if ($http_user_agent = "") {';
            $lines[] = '    return 403;';
            $lines[] = '}';
            $lines[] = '';
        }

        // IP blocking
        if ($this->blockedIps !== []) {
            $lines[] = '# Block specific IPs';
            foreach ($this->blockedIps as $ip) {
                $lines[] = sprintf('deny %s;', $ip);
            }
            $lines[] = '';
        }

        // Global rate limit
        $lines[] = '# Global rate limiting';
        $lines[] = 'location / {';
        $lines[] = sprintf('    limit_req zone=backto_global burst=%d nodelay;', $this->globalBurst);
        $lines[] = sprintf('    limit_conn backto_conn %d;', $this->maxConnPerIp);
        $lines[] = '    # ... your existing configuration (proxy_pass or fastcgi_pass)';
        $lines[] = '}';
        $lines[] = '';

        // Sensitive endpoints
        if ($this->sensitiveEndpoints !== []) {
            $endpointsPattern = implode('|', array_map(
                fn (string $ep): string => preg_quote($ep, '/'),
                $this->sensitiveEndpoints,
            ));
            $lines[] = '# Stricter rate limiting for sensitive endpoints';
            $lines[] = sprintf('location ~ ^/(%s) {', $endpointsPattern);
            $lines[] = sprintf('    limit_req zone=backto_sensitive burst=%d nodelay;', $this->sensitiveBurst);
            $lines[] = sprintf('    limit_conn backto_conn %d;', $this->maxConnPerIp);
            $lines[] = '    # ... your existing configuration (proxy_pass or fastcgi_pass)';
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    public function generateApache(): string
    {
        $lines = [];
        $lines[] = '# ============================================================';
        $lines[] = '# Bot protection — generated by BackTo Framework Security Bundle';
        $lines[] = '# Include this file in your VirtualHost or .htaccess.';
        $lines[] = '# ============================================================';
        $lines[] = '';

        // User-Agent blocking
        if ($this->blockedUserAgents !== []) {
            $pattern = implode('|', $this->blockedUserAgents);
            $lines[] = '# Block known bot User-Agents';
            $lines[] = '<IfModule mod_rewrite.c>';
            $lines[] = '    RewriteEngine On';
            $lines[] = sprintf('    RewriteCond %%{HTTP_USER_AGENT} (%s) [NC]', $pattern);
            $lines[] = '    RewriteRule .* - [F,L]';

            if ($this->blockEmptyUserAgent) {
                $lines[] = '';
                $lines[] = '    # Block empty User-Agent';
                $lines[] = '    RewriteCond %{HTTP_USER_AGENT} ^$ [NC]';
                $lines[] = '    RewriteRule .* - [F,L]';
            }

            $lines[] = '</IfModule>';
            $lines[] = '';
        }

        // IP blocking
        if ($this->blockedIps !== []) {
            $lines[] = '# Block specific IPs';
            $lines[] = '<RequireAll>';
            $lines[] = '    Require all granted';
            foreach ($this->blockedIps as $ip) {
                $lines[] = sprintf('    Require not ip %s', $ip);
            }
            $lines[] = '</RequireAll>';
            $lines[] = '';
        }

        // mod_evasive
        $lines[] = '# Rate limiting (requires mod_evasive)';
        $lines[] = '<IfModule mod_evasive24.c>';
        $lines[] = '    DOSHashTableSize    3097';
        $lines[] = sprintf('    DOSPageCount        %d', max(1, $this->sensitiveRateLimit * 3));
        $lines[] = sprintf('    DOSSiteCount        %d', max(10, $this->globalRateLimit * 5));
        $lines[] = '    DOSPageInterval     1';
        $lines[] = '    DOSSiteInterval     1';
        $lines[] = '    DOSBlockingPeriod   60';
        $lines[] = '</IfModule>';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Write the generated config to disk.
     *
     * @return bool True if the file was written successfully.
     */
    public function writeNginx(string $path): bool
    {
        return $this->fileWriter->write($path, $this->generateNginx());
    }

    /**
     * Write the generated config to disk.
     *
     * @return bool True if the file was written successfully.
     */
    public function writeApache(string $path): bool
    {
        return $this->fileWriter->write($path, $this->generateApache());
    }
}
